name: CD EMT-CORE

on:
  push:
    branches: [ deployment ]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Deploy in azure instance
        env:
            PRIVATE_KEY: ${{ secrets.AZURE_PRIVATE_KEY  }}
            HOSTNAME : "20.96.37.192"
            USER_NAME : "azureuser"
            
        run: |
          echo "$PRIVATE_KEY" 
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
          
            #Now we have got the access of Azure VM and we will start the deploy .
            ls -a
            cd ~/projects/emt-system &&
            git checkout deployment &&
            git fetch --all &&
            git reset --hard origin/deployment &&
            git pull origin deployment &&
            docker-compose up -d --build 
          '